-- Databases 1 Lab 2 - C24329646 - Creating ERDs

-- Script generated by PGAdmin ERD tool.

CREATE TABLE IF NOT EXISTS "FoodDeliveryApp"."Customer" (
    "CustomerID" SERIAL,
    "CustomerName" text,
    "Address" text,
    "Phone" character varying(14),
    PRIMARY KEY ("CustomerID")
);

CREATE TABLE IF NOT EXISTS "FoodDeliveryApp"."Restaurant" (
    "RestaurantID" SERIAL,
    "RestaurantName" text,
    "Cuisine" text,
    "Location" text,
    PRIMARY KEY ("RestaurantID")
);

CREATE TABLE IF NOT EXISTS "FoodDeliveryApp"."MenuItem" (
    "ItemID" SERIAL,
    "RestauranteID" text,
    "ItemName" text,
    "Price" money,
    "Category" text,
    PRIMARY KEY ("ItemID")
);

CREATE TABLE IF NOT EXISTS "FoodDeliveryApp"."Order" (
    "OrderID" SERIAL,
    "CustomerID" text,
    "Date" date,
    "TotalAmount" money,
    PRIMARY KEY ("OrderID")
);

CREATE TABLE IF NOT EXISTS "FoodDeliveryApp"."OrderItem" (
    "OrderID" SERIAL,
    "ItemID" text,
    "Quantity" integer
);


ALTER TABLE IF EXISTS "FoodDeliveryApp"."Customer"
ADD FOREIGN KEY ("CustomerID") REFERENCES "FoodDeliveryApp"."Order" ("CustomerID") MATCH SIMPLE
ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;

ALTER TABLE IF EXISTS "FoodDeliveryApp"."Restaurant"
ADD FOREIGN KEY ("RestaurantID") REFERENCES "FoodDeliveryApp"."MenuItem" ("RestauranteID") MATCH SIMPLE
ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;

ALTER TABLE IF EXISTS "FoodDeliveryApp"."MenuItem"
ADD FOREIGN KEY ("ItemID") REFERENCES "FoodDeliveryApp"."OrderItem" ("ItemID") MATCH SIMPLE
ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;

ALTER TABLE IF EXISTS "FoodDeliveryApp"."Order"
ADD FOREIGN KEY ("OrderID") REFERENCES "FoodDeliveryApp"."Order" ("OrderID") MATCH SIMPLE
ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;